// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANSA5ly19412pQJTAT4BvFzoBKmhZte6A',
    appId: '1:793130505913:android:70ece84da7d563e0056d68',
    messagingSenderId: '793130505913',
    projectId: 'presence-15475',
    storageBucket: 'presence-15475.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb1ZwXJPF51fa-ZOqLup-GsUFUI8JInNU',
    appId: '1:793130505913:ios:c82ed31b51afb044056d68',
    messagingSenderId: '793130505913',
    projectId: 'presence-15475',
    storageBucket: 'presence-15475.appspot.com',
    iosClientId: '793130505913-326ptqu88eitevv5dcguppaqll33u595.apps.googleusercontent.com',
    iosBundleId: 'com.abdurrahmanjun.presence',
  );
}
